apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
      - name: todo-service
        image: saalaah/todo-service-compose:1.0
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: todo-service


# cd ../todo-service
# docker build -t saalaah/todo-service:1.0 .
# docker push saalaah/todo-service:1.0